<a href="https://colab.research.google.com/github/ambikasairam/ai-learning-journey/blob/main/week_01_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 01 — Python Basics for AI

This notebook covers basic Python concepts needed for AI and ML.

## Topics
- Variables
- Data types
- Lists & dictionaries
- Functions
- Loops


In [30]:
# Variables and data types
x = 10
y = 3.5
name = "AI Learner"

print(type(x), type(y), type(name))
z=x+y
print(z, type(z))
#concatenate strings
f=name + " testing"
print(f, type(f))
#changing the type of name from strint to int
name = 10
print(x+name)

<class 'int'> <class 'float'> <class 'str'>
13.5 <class 'float'>
AI Learner testing <class 'str'>
20


In [31]:
# Lists and dictionaries
numbers = [1, 2, 3, 4]
person = {"name": "Alicia", "role": "AI Learner"}

print(numbers)
print(person["name"])


[1, 2, 3, 4]
Alicia


In [32]:
# Functions
def add(a, b):
    return a + b

add(3, 9)



12

In [53]:
# Loops
for i in range(5):
    print("Iteration:", i)

x = [1, 2, 3, 4]
for i in x:
 print("i ", i)



Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
i  1
i  2
i  3
i  4


Learning Numpy

NumPy teaches you to think in arrays, not loops.

In [39]:
import numpy as np

a = np.array([1, 2, 3, 4])
a

#2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])
b

c = np.array([[1,2,3,4],[5,6,7,8]])

#AI models mostly operate on 2D+ arrays.

#array properties
a.shape      # dimensions
a.ndim       # number of dimensions
a.size       # total elements
a.dtype
print("shape is",b.shape)   # (2, 3)
print("dim is",b.ndim)
print("size",b.size)
print("type is ", b.dtype)

# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix) # Outputs the matrix

# Access an element
element = matrix[1, 2]
print(element) # Outputs: 6

#creating common arrays
np.zeros((3, 4))      # matrix of zeros
np.ones((2, 2))       # matrix of ones


#reshaping arrays - Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])
print("original array", array)

# Reshape the array to 2x3
reshaped_array = array.reshape(2, 3)
print("Reshaped array",reshaped_array) # Outputs a reshaped 2D array




shape is (2, 3)
dim is 2
size 6
type is  int64
[[1 2 3]
 [4 5 6]]
6
original array [1 2 3 4 5 6]
Reshaped array [[1 2 3]
 [4 5 6]]


In [50]:
#slicing and dicing
a = np.array([1, 2, 3, 4])

#2D array
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a[0])
print(a[1:3])
print(b[0, 1]  )  # row 0, column 1
print(b[:, 1] )   # all rows, column 1
print(b[1, :] )   # row 1


1
[2 3]
2
[2 5]
[4 5 6]


In [36]:
import numpy as np
# arange uses step size
arange_result = np.arange(0, 10, 2)
print("arange(0, 10, 2):", arange_result)
# Output: [0 2 4 6 8]

# linspace uses number of elements
linspace_result = np.linspace(0, 10, 2)
print("linspace(0, 10, 2):", linspace_result)
# Output: [0. 10.]

# More comparable example
arange_ex = np.arange(0, 10, 2.5)
print("\narange(0, 10, 2.5):", arange_ex)
# Output: [0. 2.5 5. 7.5]

linspace_ex = np.linspace(0, 10, 5)
print("linspace(0, 10, 5):", linspace_ex)
# Output: [0. 2.5 5. 7.5 10.]

arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 10, 2): [ 0. 10.]

arange(0, 10, 2.5): [0.  2.5 5.  7.5]
linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]


In [40]:
import numpy as np

# Create an array
a = np.array([1, 2, 3])

# Add a scalar to each element using broadcasting
result = a + 5
print(result)  # Outputs: [6 7 8]

[6 7 8]


In [ ]:
#Basic Copy
import numpy as np

arr = np.array([1, 2, 3])
copy_arr = np.copy(arr)
copy_arr[0] = 99

print(arr)      # Output: [1, 2, 3]
print(copy_arr) # Output: [99, 2, 3]


In [47]:
#Basic View

import numpy as np

arr = np.array([1, 2, 3])
print(arr[0:3])
view_arr = arr.view()
view_arr[0] = 99

print(arr)      # Output: [99, 2, 3]
print(view_arr) # Output: [99, 2, 3]


[1 2 3]
[99  2  3]
[99  2  3]


In [48]:
#slicing

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
slice_copy = np.copy(arr[0:2])
print("slice_copy", slice_copy)
slice_view = arr[0:2].view()
print("slice_view", slice_view)

slice_copy[0, 0] = 99
slice_view[0, 0] = 88

print("arr",arr)         # Output: [[ 1  2]
                   #          [88  4]
                   #          [ 5  6]]
print("slice_copy",slice_copy)  # Output: [[99  2]
                   #          [ 3  4]]
print("slice_view",slice_view)  # Output: [[88  2]
                   #          [ 3  4]]


slice_copy [[1 2]
 [3 4]]
slice_view [[1 2]
 [3 4]]
arr [[88  2]
 [ 3  4]
 [ 5  6]]
slice_copy [[99  2]
 [ 3  4]]
slice_view [[88  2]
 [ 3  4]]


In [59]:
#faster loops

a=np.array([1, 2, 3, 4])

print(a*2)
print(a+1)
print(a ** 2)
print(np.sqrt(a))




[2 4 6 8]
[2 3 4 5]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]


In [61]:
#basic maths and services

a=np.array([1, 2, 3, 4])
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))


2.5
2.5
1.118033988749895
10
1
4
